//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public int IngredientID { get; set; }
        public int AmountNeeded { get; set; }
        public int AmountActuallyRecieved { get; set; }
        public Nullable<int> type_IngredientTypeID { get; set; }
        public Nullable<int> Recipe_RecipeID { get; set; }
    
        public virtual IngredientType IngredientType { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
