//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public Recipe()
        {
            this.Batches = new HashSet<Batch>();
            this.Ingredients = new HashSet<Ingredient>();
            this.RecOperations = new HashSet<RecOperation>();
        }
    
        public int RecipeID { get; set; }
        public string BrandName { get; set; }
    
        public virtual ICollection<Batch> Batches { get; set; }
        public virtual ICollection<Ingredient> Ingredients { get; set; }
        public virtual ICollection<RecOperation> RecOperations { get; set; }
    }
}
