//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.EQAuxilaries = new HashSet<EQAuxilary>();
            this.EQControlLoops = new HashSet<EQControlLoop>();
            this.EQVessels = new HashSet<EQVessel>();
            this.UnitOperations = new HashSet<UnitOperation>();
            this.Units1 = new HashSet<Unit>();
            this.Units = new HashSet<Unit>();
        }
    
        public int UnitID { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> Plant_PlantID { get; set; }
        public Nullable<int> Batch_BatchID { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual ICollection<EQAuxilary> EQAuxilaries { get; set; }
        public virtual ICollection<EQControlLoop> EQControlLoops { get; set; }
        public virtual ICollection<EQVessel> EQVessels { get; set; }
        public virtual Plant Plant { get; set; }
        public virtual ICollection<UnitOperation> UnitOperations { get; set; }
        public virtual ICollection<Unit> Units1 { get; set; }
        public virtual ICollection<Unit> Units { get; set; }
    }
}
