//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecOperation
    {
        public int RecOperationID { get; set; }
        public string WhatTheRecipeNeedsToHappen { get; set; }
        public Nullable<int> Recipe_RecipeID { get; set; }
    
        public virtual Recipe Recipe { get; set; }
    }
}
